const phase = {
  phases: [
    {
      'phase': 'Đợt 1',
      'time': 'Từ 22-01 đến 05-03',
      'sum-infected': 16,
      'num-vietnam-infected': 13,
      'num-foreigner-infected': 3,
      'num-treated': 16,
      'num-treating': 0,
      'num-dead': 0,
      'num-entry': 8,
      'num-domestic': 8,
      'entry-isolate': 0,
      'entry-not-isolate': 0,
      'community-from-entry': 7,
      'community-from-community': 7,
    },
    {
      'phase': 'Đợt 2',
      'time': 'Từ 22-01 đến 05-03',
      'sum-infected': 16,
      'num-vietnam-infected': 13,
      'num-foreigner-infected': 3,
      'num-treated': 16,
      'num-treating': 0,
      'num-dead': 0,
      'num-entry': 8,
      'num-domestic': 8,
      'entry-isolate': 0,
      'entry-not-isolate': 0,
      'community-from-entry': 7,
      'community-from-community': 7,
    },
    {
      'phase': 'Đợt 3',
      'time': 'Từ 23-07 đến nay',
      'sum-infected': 16,
      'num-vietnam-infected': 13,
      'num-foreigner-infected': 3,
      'num-treated': 16,
      'num-treating': 0,
      'num-dead': 0,
      'num-entry': 8,
      'num-domestic': 8,
      'entry-isolate': 0,
      'entry-not-isolate': 0,
      'community-from-entry': 7,
      'community-from-community': 7,
    },
  ],
  summary: {
    'time': 'Tổng hợp',
    'sum-infected': 16,
    'num-vietnam-infected': 13,
    'num-foreigner-infected': 3,
    'num-treated': 16,
    'num-treating': 0,
    'num-dead': 0,
    'num-entry': 8,
    'num-domestic': 8,
    'entry-isolate': 0,
    'entry-not-isolate': 0,
    'community-from-entry': 7,
    'community-from-community': 7,
  }
}
module.exports = phase;
